
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Sep 24 12:02:51 CDT 2013
//----------------------------------------------------

package edu.uiowa.NLP_grammar.syntaxMatch;

/** CUP generated interface containing symbol constants. */
public interface ConceptParseSym {
  /* terminals */
  public static final int OR_OP = 5;
  public static final int RPAREN = 3;
  public static final int error = 1;
  public static final int AND_OP = 4;
  public static final int LPAREN = 2;
  public static final int EOF = 0;
}

