
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon May 21 16:51:52 CDT 2018
//----------------------------------------------------

package edu.uiowa.lucene.booleanSearch;

/** CUP generated interface containing symbol constants. */
public interface BooleanParseSym {
  /* terminals */
  public static final int OR_OP = 6;
  public static final int String = 4;
  public static final int RPAREN = 3;
  public static final int error = 1;
  public static final int AND_OP = 5;
  public static final int NOT_OP = 7;
  public static final int LPAREN = 2;
  public static final int EOF = 0;
}

